name: firstflow

on: [push]

jobs:
    run-shell:
        runs-on: ubuntu-latest
        steps: 
            - name: welcome
              run: echo "hello world"
            - name: mmultiple commands
              run: |
                  node -v
                  npm -v
            - name: run python
              run: |
                  import platform
                  print(platform.processor())
              shell: python
    run-windows:
        runs-on: windows-latest
        steps:
            - name: run powershell dir
              run: Get-Location
            - name: run bash dir
              run: pwd
              shell: bash
