name: Simple Action Workflow

on: [push]

jobs:
    run-simple-action:
        runs-on: ubuntu-latest
        steps:
            - name: action 1
              id: greetMe
              uses: actions/hello-world-javascript-action@v1
              with:
                  who-to-greet: Marcin
            - name: log greeting time
              run: echo "${{steps.greetMe.outputs.time}}"

